[package]
name = "h2m_favorites"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
clap = { version = "4.5.16", features = ["derive"] }
