[package]
name = "h2m_favorites"
version = "0.2.9"
authors = ["WardLordRuby"]
description = """
A CLI Server Scraper that compiles a valid favorites.json for H2M-mod. Supports custom server queries
By: WardLordRuby <@7thWardLord Discord>"""
edition = "2021"

[package.metadata.winresource]
ProductName = "H2M Favorites"
FileDescription = "H2M-mod server scraper"
ProductVersion = "0.2.9"

[profile.release]
strip = "debuginfo"
# lto = true

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.125"
clap = { version = "4.5.16", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"]}
tracing = { version = "0.1.40", features = ["release_max_level_info"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-appender = "0.2.3"
shellwords = "1.1.0"
tokio-stream = "0.1.15"
crossterm = { version = "0.28.1", features = ["event-stream"]}
winpty-rs = "0.3.16"
winapi = "0.3.9"
# windows-sys = { version = "0.59.0", features = ["Win32"]}
# uuid = { version = "1.10.0", features = ["v4", "fast-rng"]}
# miow = "0.6.0"
# windows-sys = { version = "0.59.0", features = ["Win32_System_IO", "Win32_Foundation"]}
# mio = "1.0.2" 

[build-dependencies]
winresource = "0.1.17"