[package]
name = "h2m_favorites"
version = "0.2.0"
authors = ["WardLordRuby"]
description = """
A CLI Server Scraper that compiles a valid favorites.json for H2M-mod. Supports custom server queries
By: WardLordRuby <@7thWardLord Discord>"""
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
clap = { version = "4.5.16", features = ["derive"] }
tokio = { version = "1.39.3", features = ["rt-multi-thread", "macros"]}
futures = "0.3.30"